# Generated by Django 6.0.6 on 2026-07-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapmatch',
            name='user1_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swapmatch',
            name='user2_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swapmatch',
            name='user3_verified',
            field=models.BooleanField(default=False),
        ),
    ]
